import { Modelo1, Modelo2, Modelo3 } from "../../assets";
import { ProductList } from "../../interfaces/listProduct.interface";

export const productList: ProductList[] = [
  {
    title: "Camiseta Casual",
    price: "S/ 89.90",
    promotion: true,
    favorite: false,
    image: Modelo1,
    colors: ["#FF5733", "#C70039", "#900C3F"],
  },
  {
    title: "Jeans Slim Fit",
    price: "S/ 149.90",
    promotion: false,
    favorite: true,
    image: Modelo2,
    colors: ["#2980B9", "#2ECC71"],
  },
  {
    title: "Zapatillas Deportivas",
    price: "S/ 199.90",
    promotion: true,
    favorite: true,
    image: Modelo3,
    colors: ["#F1C40F", "#E67E22", "#2E4053"],
  },
  {
    title: "Chaqueta de Cuero",
    price: "S/ 349.90",
    promotion: false,
    favorite: false,
    image: Modelo1,
    colors: ["#34495E"],
  },
  {
    title: "Gorra Unisex",
    price: "S/ 39.90",
    promotion: true,
    favorite: false,
    image: Modelo2,
    colors: ["#1ABC9C", "#16A085", "#F39C12"],
  },
  {
    title: "Short Deportivo",
    price: "S/ 79.90",
    promotion: true,
    favorite: true,
    image: Modelo3,
    colors: ["#8E44AD", "#9B59B6"],
  },
  {
    title: "Polera de Lana",
    price: "S/ 129.90",
    promotion: false,
    favorite: false,
    image: Modelo1,
    colors: ["#BDC3C7", "#95A5A6"],
  },
  {
    title: "Vestido Elegante",
    price: "S/ 249.90",
    promotion: true,
    favorite: true,
    image: Modelo2,
    colors: ["#D35400", "#E74C3C", "#3498DB"],
  },
  {
    title: "Cinturón Cuero",
    price: "S/ 59.90",
    promotion: false,
    favorite: false,
    image: Modelo3,
    colors: ["#7F8C8D", "#2C3E50"],
  },
  {
    title: "Pantalón de Vestir",
    price: "S/ 179.90",
    promotion: false,
    favorite: true,
    image: Modelo1,
    colors: ["#27AE60", "#2ECC71", "#1F618D"],
  },
  {
    title: "Blusa Formal",
    price: "S/ 99.90",
    promotion: true,
    favorite: true,
    image: Modelo2,
    colors: ["#F39C12", "#E74C3C"],
  },
  {
    title: "Chompa Unisex",
    price: "S/ 149.90",
    promotion: false,
    favorite: false,
    image: Modelo3,
    colors: ["#34495E", "#16A085", "#1ABC9C"],
  },
];
